# Generated by Django 2.0.7 on 2019-10-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'A. Category'},
        ),
    ]
