# Generated by Django 2.0.7 on 2019-10-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_auto_20191022_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
